# Generated by Django 5.0.4 on 2024-04-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
