# Generated by Django 5.0.4 on 2024-04-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friendrequest",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
